name: Build V8

on:
  push:
    branches: [ master ]
    paths-ignore:
    - 'LICENSE'
    - '**.md'

jobs:

  version_finder:
    name: Get version number
    runs-on: ubuntu-latest
    outputs:
      v8_version: ${{ steps.got_version.outputs.version }}
    steps:
    - uses: actions/checkout@v2
    - id: got_version
      run: |
        cd $GITHUB_WORKSPACE
        pip install pandas
        version=$(python ./get_version.py)
  #      version=8.1.307.31
        echo "::set-output name=version::$version"
  
  build_linux:
    name: Linux
    runs-on: ubuntu-18.04
    needs: version_finder
    steps:
    - uses: actions/checkout@v2
    - name: Run build script
      run: |
        cd $GITHUB_WORKSPACE
        sh ./v8-linux.sh ${{ needs.version_finder.outputs.v8_version }}
    - uses: actions/upload-artifact@v2
      with:
        name: v8_linux_x86-64_${{ needs.version_finder.outputs.v8_version }}
        path: '~/v8/v8/out.gn/x64.release/*.so'

  build_android_arm_v8:
    name: Android (arm64-v8a)
    runs-on: ubuntu-18.04
    needs: version_finder
    steps:
    - uses: actions/checkout@v2
    - name: Run build script
      run: |
        cd $GITHUB_WORKSPACE
        sh ./v8-android-arm-v8.sh ${{ needs.version_finder.outputs.v8_version }}
    - uses: actions/upload-artifact@v2
      with:
        name: v8_android_arm64-v8a_${{ needs.version_finder.outputs.v8_version }}
        path: '~/v8/v8/out.gn/arm64.release/*.so'

  build_android_arm_v7:
    name: Android (armeabi-v7a)
    runs-on: ubuntu-18.04
    needs: version_finder
    steps:
    - uses: actions/checkout@v2
    - name: Run build script
      run: |
        cd $GITHUB_WORKSPACE
        sh ./v8-android-arm-v7.sh ${{ needs.version_finder.outputs.v8_version }}
    - uses: actions/upload-artifact@v2
      with:
        name: v8_android_armeabi-v7a_${{ needs.version_finder.outputs.v8_version }}
        path: '~/v8/v8/out.gn/arm.release/*.so'
  
  build_android_x86_64:
    name: Android (x86-64)
    runs-on: ubuntu-18.04
    needs: version_finder
    steps:
    - uses: actions/checkout@v2
    - name: Run build script
      run: |
        cd $GITHUB_WORKSPACE
        sh ./v8-android-x86-64.sh ${{ needs.version_finder.outputs.v8_version }}
    - uses: actions/upload-artifact@v2
      with:
        name: v8_android_x86-64_${{ needs.version_finder.outputs.v8_version }}
        path: '~/v8/v8/out.gn/x64.release/*.so'

  build_android_x86:
    name: Android (x86)
    runs-on: ubuntu-18.04
    needs: version_finder
    steps:
    - uses: actions/checkout@v2
    - name: Run build script
      run: |
        cd $GITHUB_WORKSPACE
        sh ./v8-android-x86.sh ${{ needs.version_finder.outputs.v8_version }}
    - uses: actions/upload-artifact@v2
      with:
        name: v8_android_x86_${{ needs.version_finder.outputs.v8_version }}
        path: '~/v8/v8/out.gn/ia32.release/*.so'

  build_macos:
    name: macOS
    runs-on: macos-10.15
    needs: version_finder
    steps:
    - uses: actions/checkout@v2
    - name: Run build script
      run: |
        cd $GITHUB_WORKSPACE
        sh ./v8-macos.sh ${{ needs.version_finder.outputs.v8_version }}
    - uses: actions/upload-artifact@v2
      with:
        name: v8_macos_${{ needs.version_finder.outputs.v8_version }}
        path: '~/v8/v8/out.gn/x64.release/*.dylib'

  build_windows:
    name: Windows
    runs-on: windows-2019
    needs: version_finder
    steps:
    - uses: actions/checkout@v2
    - name: Run build script
      shell: cmd
      run: |
        cd %GITHUB_WORKSPACE%
        call .\v8-windows.cmd ${{ needs.version_finder.outputs.v8_version }}
    - uses: actions/upload-artifact@v2
      with:
        name: v8_windows_${{ needs.version_finder.outputs.v8_version }}
        path: 'v8/v8/out.gn/x64.release/*.dll'

  headers_and_documentation:
    name: Headers and Documentation
    runs-on: ubuntu-18.04
    needs: version_finder
    steps:
    - uses: actions/checkout@v2
    - name: Generate documentation
      run: |
        cd $GITHUB_WORKSPACE
        sh ./v8-docs.sh ${{ needs.version_finder.outputs.v8_version }}
    - uses: actions/upload-artifact@v2
      with:
        name: v8_headers_${{ needs.version_finder.outputs.v8_version }}
        path: '~/v8/v8/include'
    - uses: actions/upload-artifact@v2
      with:
        name: v8_documentation_${{ needs.version_finder.outputs.v8_version }}
        path: '~/docs'