name: Build V8

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build V8 for Linux
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2

    - name: Run
      run: |
        cd $GITHUB_WORKSPACE
        sh ./v8-linux.sh

    - uses: actions/upload-artifact@v2
      with:
        path: '~/v8/v8-linux.zip'

